apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
  namespace: nginx
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      containers:
      - name: demo-job-container
        image: busybox
        command: ["sh", "-c", "echo Hello ram ram"]
      restartPolicy: Never

