kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: intern-manager-role-binding
  namespace: nginx
subjects:
- kind: User
  name: intern
  namespace: nginx
roleRef:
  kind: Role
  name: manager
  apiGroup: rbac.authorization.k8s.io

